sorgenti/g3w-admin-catalog/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


from . import views

app_name = 'catalog'

urlpatterns = [
    re_path(r'^$', login_required(views.CatalogList.as_view()), name="csw_index"),
    re_path(r'^csw/(?P<catalog_pk>[\d]+)/$', csrf_exempt(views.CatalogCswView.as_view()), name="csw_by_pk"),
    re_path(r'^csw/(?P<catalog_slug>[-_\w]+)/$', csrf_exempt(views.CatalogCswView.as_view()), name="csw_by_slug"),
    re_path(r'^rndt/(?P<catalog_pk>[\d]+)/$', csrf_exempt(views.CatalogRndtView.as_view()), name="rndt_by_pk"),
    re_path(r'^rndt/(?P<catalog_slug>[-_\w]+)/$', csrf_exempt(views.CatalogRndtView.as_view()), name="rndt_by_slug"),
    re_path(r'^rndt_service_metadata/(?P<catalog_pk>[\d]+)/$', csrf_exempt(views.CatalogRndtServiceView.as_view()), name="rndt_service_by_pk"),
    re_path(r'^rndt_service_metadata/(?P<catalog_slug>[-_\w]+)/$', csrf_exempt(views.CatalogRndtServiceView.as_view()), name="rndt_service_by_slug"),
    # Admin
    re_path(r'^(?P<pk>[\d]+)/$', login_required(views.CatalogDetail.as_view()), name="detail"),
    re_path(r'^update/(?P<pk>[\d]+)/$', login_required(views.CatalogUpdate.as_view()), name="update"),
    re_path(r'^create/$', login_required(views.CatalogCreate.as_view()), name="create"),
    re_path(r'^delete/(?P<pk>[\d]+)/$', login_required(views.CatalogDelete.as_view()), name="delete"),
    re_path(r'^record/(?P<pk>[\d]+)/$', login_required(views.RecordUpdate.as_view()), name="record_update"),
    path('eulicense/', login_required(views.EULicenseView.as_view()), name="csw_eulicense_list"),

]

sorgenti/g3w-admin-catalog/templates/catalog/catalog_confirm_delete.html
{% extends "base.html" %}
{% comment %}
Confirm delete template for CSW catalogs
{% endcomment %}
{% load i18n %}

{% block page_header %}
        <h1>{% trans 'Catalog' %}
            {{ object.name }}
        <small>{% trans "deleting" %}</small>
        </h1>
{% endblock %}

{% block main_content %}

<form method="post">{% csrf_token %}
    <p>{% trans 'Are you sure you want to delete' %} <i>"{{ object.name }}"</i>?</p>
    <input class="btn btn-warning" type="submit" value="{% trans 'Confirm'%}">
</form>


{% endblock %}

sorgenti/g3w-admin-catalog/templates/catalog/catalog_detail.html
{% extends "base.html" %}
{% comment %}
Detail template for CSW catalogs
{% endcomment %}
{% load i18n %}

{% block page_header %}
        <h1>{% trans 'Catalog' %}

        <small>{{ object.name }}</small>
        </h1>
{% endblock %}

{% block main_content %}

{% if user.is_superuser %}
<div class="row">
<div class="col-md-12 col-xs-12">
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Catalog {{ object.name }}
                <a href="{% url 'catalog:update' catalog.pk %}" data-toggle="tooltip" data-placement="top" title="{% trans 'Edit' %}"><i class="ion ion-edit"></i></a>
                <a href="{% url 'catalog:delete' catalog.pk %}" data-toggle="tooltip" data-placement="top" title="{% trans 'Delete' %}"><i class="ion ion-trash-b"></i></a>
            </h3>
        </div>
        <div class="box-body">
            <a class="btn btn-default btn-sm" target="_blank" href="{% url 'catalog:csw_by_slug' catalog.slug %}?SERVICE=CSW&amp;REQUEST=GetCapabilities">GetCapabilities</a>
            <a class="btn btn-info btn-sm" target="_blank" href="{% url 'catalog:csw_by_slug' catalog.slug %}?SERVICE=CSW&amp;REQUEST=GetCapabilities&amp;ELEMENTSNAME=full&amp;OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd">GetCapabilities Inspire</a>
            {% if catalog.rndt_enabled %}<a class="btn btn-warning btn-sm" target="_blank" href="{% url 'catalog:rndt_by_slug' catalog.slug %}?SERVICE=CSW&amp;REQUEST=GetCapabilities&amp;ELEMENTSNAME=full&amp;OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd">Get Catabilities RNDT</a>{% endif %}
            <a class="btn bg-purple btn-sm" target="_blank" href="{% url 'catalog_api:pod_by_slug' catalog.slug %}">DCAT_US (Project Open Data v1.1)</a>
        </div>
    </div>
</div>
</div>
{% endif %}

<div class="row">
<div class="col-md-12">
<div class="box box-success">
<div class="box-header with-border"><h3 class="box-title">{% trans 'Catalog records'%}</h3></div>
<div class="box-body">

<p>
    <strong>{% trans "Records" %}: {{ catalog.record_set.count }}</strong>
</p>

<table class="table" id="record-catalog-{{ catalog.slug }}" data-widget-type="dataTable">
    <thead>
        <tr>
            <th>{% trans 'Title' %}</th>
            <th>{% trans 'Access' %}</th>
            <th>{% trans 'Records' %}</th>
        </tr>
    </thead>
    <tbody>
        {% for record in catalog.record_set.all %}
        <tr>
            <td>{{ record.title }}</td>
            <td><a href="{% url 'catalog:record_update' record.pk %}">{{ record.rndt_dataset_identifier }}</a></td>
            <td>
                <a class="btn btn-default btn-xs" target="_blank" href="{% url 'catalog:csw_by_slug' catalog.slug %}?service=CSW&version=2.0.2&request=GetRecordById&outputFormat=application%2Fxml&outputSchema=http%3A%2F%2Fwww.opengis.net%2Fcat%2Fcsw%2F2.0.2&elementsetname=full&id={{ record.identifier }}">GetRecordById</a>
                {% if catalog.inspire_enabled %}<a class="btn btn-info btn-xs" target="_blank" href="{% url 'catalog:csw_by_slug' catalog.slug %}?service=CSW&version=2.0.2&request=GetRecordById&outputFormat=application%2Fxml&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&elementsetname=full&id={{ record.identifier }}">GetRecordById Inspire</a>{% endif %}
                {% if catalog.rndt_enabled %}
                <a class="btn btn-warning btn-xs" target="_blank" href="{% url 'catalog:rndt_by_slug' catalog.slug %}?service=CSW&version=2.0.2&request=GetRecordById&outputFormat=application%2Fxml&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&elementsetname=full&id={{ record.identifier }}">GetRecordById RNDT</a>
                <a class="btn btn-warning btn-xs" target="_blank" href="{% url 'catalog:rndt_service_by_slug' catalog.slug %}">RNDT Service Metadata</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

</div>
</div>
</div>
</div>

<div class="row">
<div class="col-md-12">
<div class="box box-success">
    <div class="box-header with-border"><h3 class="box-title">{% trans 'Catalog data' %}</h3></div>
<div class="box-body">
    <table class="table" id="catalog-data" data-widget-type="dataTable">
    <thead>
        <tr>
            <th>{% trans 'Param' %}</th>
            <th>{% trans 'Value' %}</th>
        </tr>
    </thead>
    <tbody>
    {% for name, value in object.get_fields %}
        <tr><td>{% trans name %}</td><td>{% if value != 'None' %}{{ value }}{% else %}<span style="color: #999999">{% trans 'Not set' %}</span>{% endif %}</td></tr>
    {% endfor %}
    </tbody>
    </table>
</div>
</div>
</div>

</div>

<a type="submit" class="btn btn-lg btn-default" href="{% url 'catalog:csw_index' %}">{% trans "Back" %}</a>



{% endblock %}

sorgenti/g3w-admin-catalog/templates/catalog/catalog_form.html
{% extends "base.html" %}
{% comment %}
template for CSW catalogs
{% endcomment %}
{% load g3wadmin_tags %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block page_header %}
        <h1>{% trans 'Catalog' %}
            {{ form.instance.name }}
        <small>{% trans "metadata" %} </small>
        </h1>
{% endblock %}

{% block main_content %}

{% include "catalog/include/introduction.html" %}

<form method="post" id="catalog-form"  enctype="multipart/form-data">
    {% if form.errors %}
        <div class="row">
            <div class="col-md-12">
            <div class="alert alert-danger alert-dismissable">
                <h4><i class="icon fa fa-ban"></i> {% trans 'Alert' %}!</h4>
                    {% trans 'Some errors on form. Check it and send again.' %}
              </div>
            </div>
        </div>
    {% endif %}
    {% crispy form %}
    {% g3wadmin_add_button_form%}
</form>


{% endblock %}

sorgenti/g3w-admin-catalog/templates/catalog/catalog_list.html
{% extends "base.html" %}
{% comment %}
Index template for CSW catalogs
{% endcomment %}
{% load i18n %}

{% block page_header %}
        <h1>{% trans 'CSW published catalogs' %}
        </h1>
{% endblock %}

{% block main_content %}


<div class="row">
<div class="col-md-12">
<div class="box box-success">
<div class="box-header with-border">
    <a href="{% url 'catalog:create' %}" class="btn btn-info"><i class="ion ion-plus-circled"></i> {% trans "New catalog" %}</a>
</div>
<div class="box-body">
    {% if object_list.count %}
    <table id="csw-catalog-list" class="table" data-widget-type="dataTable">
        <thead>
        <tr>
            <th>{% trans 'Actions' %}</th>
            <th>{% trans 'Catalog' %}</th>
            <th>{% trans 'N record' %}</th>
            <th>{% trans 'Capabilities' %}</th>
        </tr>
        </thead>
        <tbody>
        {% for catalog in object_list %}
            <tr>
                <td>
                    <span class="col-xs-4 icon">
                        <a href="{% url 'catalog:detail' catalog.pk %}" data-toggle="tooltip" data-placement="top" title="{% trans 'Show records' %}"><i class="ion ion-android-list"></i></a>
                    </span>
                    {% if user.is_superuser %}
                    <span class="col-xs-4 icon">
                        <a href="{% url 'catalog:update' catalog.pk %}" data-toggle="tooltip" data-placement="top" title="{% trans 'Edit' %}"><i class="ion ion-edit"></i></a>
                    </span>
                    <span class="col-xs-4 icon">
                        <a href="{% url 'catalog:delete' catalog.pk %}" data-toggle="tooltip" data-placement="top" title="{% trans 'Delete' %}"><i class="ion ion-trash-b"></i></a>
                    </span>
                    {% endif %}
                </td>
                <td><strong>{{ catalog.name }}</strong></td>
                <td>{{ catalog.record_set.count }}</td>
                <td>
                    <a class="btn btn-default btn-sm" target="_blank" href="{% url 'catalog:csw_by_slug' catalog.slug %}?SERVICE=CSW&amp;REQUEST=GetCapabilities">GetCapabilities</a>&nbsp;
                    <a class="btn btn-info btn-sm" target="_blank" href="{% url 'catalog:csw_by_slug' catalog.slug %}?SERVICE=CSW&amp;REQUEST=GetCapabilities&amp;ELEMENTSNAME=full&amp;OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd">GetCapabilities Inspire</a>
                    {% if catalog.rndt_enabled %}<a class="btn btn-warning btn-sm" target="_blank" href="{% url 'catalog:rndt_by_slug' catalog.slug %}?SERVICE=CSW&amp;REQUEST=GetCapabilities&amp;ELEMENTSNAME=full&amp;OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd">Get Catabilities RNDT</a>{% endif %}
                    <a class="btn bg-purple btn-sm" target="_blank" href="{% url 'catalog_api:pod_by_slug' catalog.slug %}" >DCAT_US (Project Open Data v1.1)</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="alert alert-info">{% trans "There are no CSW published catalogs" %}</div>
    {% endif %}

</div>
<div class="box-footer">
    <p><b>{% trans 'Important' %}</b>! {% trans 'The projects you want to use for metadata have to be public, exposed by Anonymoususer.' %}</p>
</div>
</div>
</div>
</div>

{% endblock %}

sorgenti/g3w-admin-catalog/templates/catalog/eulicense_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page_header %}
        <h1>{% trans 'Europe Union Data License' %}
        </h1>
{% endblock %}

{% block main_content %}

<div class="row">
<div class="col-md-12">
{% for o in object_list %}
    <div class="box box-primary">
        <div class="box-header with-border">
            <h4 class="box-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#{{ o.op_code }}">
                    {{ o.op_code }}
                </a>
            </h4>
        </div>
        <div id="{{ o.op_code }}" class="panel-collapse collapse in">
            <div class="box-body">
                <p>{{ o.definition }}</p>
                <p><a href="{{ o.url }}" target="_blank">{{ o.url }}</a></p>
            </div>
        </div>
        </div>
{% endfor %}
    </div>

</div>


{% endblock %}

sorgenti/g3w-admin-catalog/templates/catalog/record_form.html
{% extends "base.html" %}
{% comment %}
template for CSW records
{% endcomment %}
{% load g3wadmin_tags %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block page_header %}
        <h1>Record

        <small>{% trans "layer metadata" %} {{ form.instance.title }}</small>
        </h1>
{% endblock %}

{% block main_content %}

{% include "catalog/include/introduction.html" %}

<form method="post" id="catalog-form"  enctype="multipart/form-data">
    {% if form.errors %}
        <div class="row">
            <div class="col-md-12">
            <div class="alert alert-danger alert-dismissable">
                <h4><i class="icon fa fa-ban"></i> {% trans 'Alert' %}!</h4>
                    {% trans 'Some errors on form. Check it and send again.' %}
              </div>
            </div>
        </div>
    {% endif %}
    {% crispy form %}
    {% g3wadmin_add_button_form%}
</form>
{% endblock %}